### ISSUE TITLE
data testdata

### ISSUE THREAD

**Issue by heylf** [heylf/spatialxe#2]
### Description of feature

Description of feature
Generate a test data set

https://www.10xgenomics.com/datasets/fresh-frozen-mouse-brain-for-xenium-explorer-demo-1-standard (still 3.5 GB)

**Comment by khersameesh24** [comment]
[https://docs.google.com/document/d/1HhsUL76LUadeqWEf0MBxaORvQIN_dJSZPM7Unb8amnk/edit](url)

[Spatialxe example dataset.docx](https://github.com/heylf/spatialxe/files/15161495/Spatialxe.example.dataset.docx)

**Comment by heylf** [comment]
Test data generated and finished.
